name: deploy personal blog

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: build blogs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > dist/.nojekyll

      - name: deploy blogs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
